testname: webMUSHRA Example
testId: default_example
bufferSize: 2048
stopOnErrors: true
showButtonPreviousPage: true
remoteService: service/write.php


pages:
    - type: generic
      id: first_page
      name: Welcome
      content: Welcome to webMUSHRA!       
    - type: mushra_phoneme
      id: trial1
      name: MUSHRA Phoneme
      content: First, lock down on any region (ideally 1 to 3 words) where hallucination seems to exist. Then, press the "unfreeze" button to start inputting scores. When you're done, press "Next" to proceed.
      showWaveform: true
      enableLooping: true 
      reference: configs/resources/audio/LJ001-0056.wav
      createAnchor35: false
      createAnchor70: false
      stimuli:
          C1: configs/resources/audio/LJ001-0056_halu.wav
    - type: finish
      name: Thank you
      content: Thank you for attending!
      showResults: true
      writeResults: true
      questionnaire:
          - type: text
            label: eMail
            name: email
          - type: number
            label: Age
            name: age
            min: 0
            max: 100
            default: 30
          - type: likert
            name: gender
            label: Gender
            response:
             - value: female
               label: Female
             - value: male
               label: Male
             - value: other
               label: Other
